feat(meta): Format code

diff --git a/scripts/install_pkgs b/scripts/install_pkgs
--- a/scripts/install_pkgs
+++ b/scripts/install_pkgs
@@ -18,54 +18,54 @@ pkg_mgr_list="apt-get yum pacman"
 
 # Checks available package manager
 check_pkg_mgr() {
-	for pkg_mgr in $pkg_mgr_list; do
-		if command -v "$pkg_mgr" >/dev/null 2>&1; then
-			echo "$pkg_mgr"
-			return
-		fi
-	done
+    for pkg_mgr in $pkg_mgr_list; do
+        if command -v "$pkg_mgr" >/dev/null 2>&1; then
+            echo "$pkg_mgr"
+            return
+        fi
+    done
 
-	echo "Your package manager is not supported!" >&2
-	exit 1
+    echo "Your package manager is not supported!" >&2
+    exit 1
 }
 
 # Populates "install" and "clean" vars
 case $(check_pkg_mgr) in
 apt-get)
-	install='DEBIAN_FRONTEND=noninteractive \
+    install='DEBIAN_FRONTEND=noninteractive \
             && apt-get update -qq \
             && apt-get install -y --no-install-recommends $@'
-	clean='apt-get clean \
+    clean='apt-get clean \
             && rm -rf /var/lib/apt/lists /var/cache/apt/archives'
-	;;
+    ;;
 yum)
-	install='yum install -y --setopt=tsflags=nodocs $@'
-	clean='yum clean all -y \
+    install='yum install -y --setopt=tsflags=nodocs $@'
+    clean='yum clean all -y \
             && rm -rf /var/cache/yum'
-	;;
+    ;;
 pacman)
-	install='pacman -Sy --needed --noconfirm $@'
-	clean='pacman -Scc --noconfirm && \
+    install='pacman -Sy --needed --noconfirm $@'
+    clean='pacman -Scc --noconfirm && \
             rm -rf /var/cache/pacman/pkg/*'
-	;;
+    ;;
 esac
 
 # Runs install retrying if fails
 until [ $n -gt $max ]; do
-	set +e
-	(eval "$install")
-	code=$?
-	set -e
+    set +e
+    (eval "$install")
+    code=$?
+    set -e
 
-	if [ $code -eq 0 ]; then
-		break
-	fi
-	if [ $n -eq $max ]; then
-		exit $code
-	fi
+    if [ $code -eq 0 ]; then
+        break
+    fi
+    if [ $n -eq $max ]; then
+        exit $code
+    fi
 
-	echo "Install failed, retrying..."
-	n=$((n + 1))
+    echo "Install failed, retrying..."
+    n=$((n + 1))
 done
 
 # Removes package manager trash
