fix(meta): Use spaces instead of tabs

diff --git a/scripts/vm_recreate b/scripts/vm_recreate
--- a/scripts/vm_recreate
+++ b/scripts/vm_recreate
@@ -12,8 +12,8 @@ ssh_port=22
 
 # Checks Vagrantfile
 if [ ! -e Vagrantfile ]; then
-	echo "Vagrantfile is missing!" >&2
-	exit 1
+    echo "Vagrantfile is missing!" >&2
+    exit 1
 fi
 
 # Recreate VMs
@@ -21,19 +21,19 @@ vagrant destroy --force
 vagrant up
 
 for vm in "$@"; do
-	# Removes previous known_hosts entries
-	ssh-keygen -f "${HOME}/.ssh/known_hosts" -R "${vm}"
+    # Removes previous known_hosts entries
+    ssh-keygen -f "${HOME}/.ssh/known_hosts" -R "${vm}"
 
-	# Awaits VM ssh port availability
-	until nc -z -w2 "${vm}" "${ssh_port}"; do
-		echo "Awaiting ${vm}..."
-		sleep 2
-	done
+    # Awaits VM ssh port availability
+    until nc -z -w2 "${vm}" "${ssh_port}"; do
+        echo "Awaiting ${vm}..."
+        sleep 2
+    done
 
-	# Tests connection
-	# -n: Dry run
-	# -o StrictHostKeyChecking=accept-new: Skips prompt to accept connection
-	ssh -n -o StrictHostKeyChecking=accept-new "vagrant@${vm}" >/dev/null 2>&1
+    # Tests connection
+    # -n: Dry run
+    # -o StrictHostKeyChecking=accept-new: Skips prompt to accept connection
+    ssh -n -o StrictHostKeyChecking=accept-new "vagrant@${vm}" >/dev/null 2>&1
 done
 
 exit 0
